/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPortfolioItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getVisitCounter' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitCounter' : IDL.Func([], [], []),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getVisitCounter' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitCounter' : IDL.Func([], [], []),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };